.PYTHON: update

update: 
	curl https://download.immersivetranslate.com/immersive-translate.user.js -o Client/IMS/Resources/immersive-translate.user.js

updatedev: 
	curl http://localhost:8000/immersive-translate.user.js -o Client/IMS/Resources/immersive-translate.user.js