# Uncomment the next line to define a global platform for your project
platform:ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Client' do
  use_frameworks!
  pod 'WCDB.swift'
  pod 'LTXiOSUtils', :git => 'git@github.com:Coder-Star/LTXiOSUtils.git', :branch => 'master'
  pod 'CSAPIService/Core', '0.1.0'
  pod 'BetterCodable', '0.4.0'
  pod 'SwiftyJSON', '4.0.0'
  pod 'AttributedString', '3.3.5'
  pod 'KeychainAccess', "4.2.2"
  pod 'ZLPhotoBrowser', '4.5.7'
  pod 'Swime', '3.0.6'
#  pod 'LookinServer', '1.0.4'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
              if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
              end
            end
        end
    end
end
