# Uncomment the next line to define a global platform for your project
platform:ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Client' do
  use_frameworks!
  pod 'CocoaDebug'
  pod 'WCDB.swift'
end